# Get aws linux & install common packages
FROM amazonlinux:latest AS osLayer
WORKDIR /workspace/

# Install updates & things around node
RUN yum update -y \
    && yum install -y amazon-linux-extras gcc-c++ make git aws-cli tar time hostname jq

# Install java-16
RUN rpm --import https://yum.corretto.aws/corretto.key \
    && curl -L -o /etc/yum.repos.d/corretto.repo https://yum.corretto.aws/corretto.repo \
    && yum install -y java-16-amazon-corretto-devel \
    && yum update -y 

# Install app
RUN aws s3 cp s3://bandcloud/app/REST_API.tar.gz ./ \
    && tar -xf REST_API.tar.gz

# Run app
WORKDIR /workspace/build
#EXPOSE 8080
#RUN java -jar libs/service_testing-0.0.1.jar